"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import ectf25_design.cryptosystem as cryptosystem
import struct
import json
import time

from ectf25.utils.decoder import *


class Encoder:
    def __init__(self, secrets: bytes):
        """
        You **may not** change the arguments or returns of this function!

        :param secrets: Contents of the secrets file generated by
            ectf25_design.gen_secrets
        """
        secrets = json.loads(secrets)

        self.trees = {
            channel: cryptosystem.Tree(
                root_key=bytes.fromhex(secrets["root_keys"][str(channel)])
            )
            for channel in secrets["channels"]
        }

    def encode(self, channel: int, frame: bytes, timestamp: int) -> bytes:
        """The frame encoder function

        This will be called for every frame that needs to be encoded before being
        transmitted by the satellite to all listening TVs

        You **may not** change the arguments or returns of this function!

        :param channel: 16b unsigned channel number. Channel 0 is the emergency
            broadcast that must be decodable by all channels.
        :param frame: Frame to encode. Max frame size is 64 bytes.
        :param timestamp: 64b timestamp to use for encoding. **NOTE**: This value may
            have no relation to the current timestamp, so you should not compare it
            against the current time. The timestamp is guaranteed to strictly
            monotonically increase (always go up) with subsequent calls to encode

        :returns: The encoded frame, which will be sent to the Decoder
        """
        # For the emergency channel, broadcast in plaintext.
        if channel == 0:
            return struct.pack("<I", channel) + frame

        frame_key = self.trees[channel].frame_key(timestamp)
        nonce = cryptosystem.get_nonce()

        length = (
            4  # Channel
            + 8  # Timestamp
            + cryptosystem.NONCE_LEN  # Nonce
            + 1  # Encrypted Frame Length
            + len(frame)  # Encrypted Frame Data
            + cryptosystem.AUTHTAG_LEN  # AuthTag
        )

        aad = b"%D" + struct.pack(
            f"<HIQ{cryptosystem.NONCE_LEN}s", length, channel, timestamp, nonce
        )
        encrypted_frame = struct.pack(f"<B", len(frame)) + frame
        encrypted_frame, tag = cryptosystem.encrypt(
            frame_key, nonce, encrypted_frame, aad
        )

        return (
            struct.pack(f"<IQ{cryptosystem.NONCE_LEN}s", channel, timestamp, nonce)
            + tag
            + encrypted_frame
        )


def main(bench_encode=False, bench_decode=False):
    """A test main to one-shot encode a frame

    This function is only for your convenience and will not be used in the final design.

    After pip-installing, you should be able to call this with:
        python3 -m ectf25_design.encoder path/to/test.secrets 1 "frame to encode" 100
    """
    parser = argparse.ArgumentParser(prog="ectf25_design.encoder")
    parser.add_argument(
        "secrets_file", type=argparse.FileType("rb"), help="Path to the secrets file"
    )
    parser.add_argument("channel", type=int, help="Channel to encode for")
    parser.add_argument("frame", help="Contents of the frame")
    parser.add_argument("timestamp", type=int, help="64b timestamp to use")
    args = parser.parse_args()

    encoder = Encoder(args.secrets_file.read())
    if not bench_encode and not bench_decode:
        print(repr(encoder.encode(args.channel, args.frame.encode(), args.timestamp)))
        return

    if bench_encode:
        import random

        total, N = 0, 10_000
        for _ in range(N):
            frame = cryptosystem.random_bytes(64)
            timestamp = random.randint(0, 2**64 - 1)
            start = time.time()
            encoder.encode(1, frame, timestamp)
            end = time.time()
            total += end - start

        print(f"Time for {N} encodings: {total}sec\n  aka {N/total} frames/sec")

    if bench_decode:
        import random

        decoder = DecoderIntf("/dev/ttyACM0")
        total, maximum, N = 0, 0, 1_000
        for _ in range(N):
            frame = cryptosystem.random_bytes(64)
            timestamp = random.randint(0, 2**64 - 1)
            enc_frame = encoder.encode(args.channel, frame, timestamp)
            start = time.time()
            dec_frame = decoder.decode(enc_frame)
            end = time.time()
            maximum = end - start if end - start > maximum else maximum
            assert frame == dec_frame and enc_frame != dec_frame
            total += end - start
        print(
            f"Time for {N} decodes: {total}sec\n  aka {N/total} frames/sec\n  max_time: {maximum} sec"
        )


if __name__ == "__main__":
    main()
