"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
from ectf25_design import cryptosystem
import json
from pathlib import Path
import struct
import time

from loguru import logger


def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription.

    The output of this will be passed to the Decoder using ectf25.tv.subscribe

    :param secrets: Contents of the secrets file generated by ectf25_design.gen_secrets
    :param device_id: Device ID of the Decoder
    :param start: First timestamp the subscription is valid for
    :param end: Last timestamp the subscription is valid for
    :param channel: Channel to enable
    """
    secrets = cryptosystem.Secrets.parse(secrets)
    tree = secrets.get_tree(channel)

    subtree = tree.minimal_tree(start, end)
    subscription = subtree.get_subscription()

    signing_key = secrets.signing_key

    shared_key = cryptosystem.hash(
        secrets.shared_key_root + struct.pack(">I", device_id)
    )[: cryptosystem.KEY_LEN]

    nonce = cryptosystem.get_nonce()

    length = (
        cryptosystem.NONCE_LEN  # Nonce
        + 4  # Encrypted Update Channel
        + 8  # Encrypted Update Start
        + 8  # Encrypted Update End
        + len(subscription)  # Encrypted Update Subscription
        + cryptosystem.AUTHTAG_LEN  # AuthTag
        + cryptosystem.SIG_LEN  # Signature
    )

    header = b"%S" + struct.pack("<H", length)
    aad = header + struct.pack(f"<{cryptosystem.NONCE_LEN}s", nonce)

    subscription = struct.pack("<IQQ", channel, start, end) + subscription
    enc_subscription, tag = cryptosystem.encrypt(shared_key, nonce, subscription, aad)

    body = struct.pack(f"{cryptosystem.NONCE_LEN}s", nonce) + tag + enc_subscription
    signature = cryptosystem.sign(signing_key, header + body)

    return body + signature


def parse_args():
    """Define and parse the command line arguments

    NOTE: Your design must not change this function
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Force creation of subscription file, overwriting existing file",
    )
    parser.add_argument(
        "secrets_file",
        type=argparse.FileType("rb"),
        help="Path to the secrets file created by ectf25_design.gen_secrets",
    )
    parser.add_argument("subscription_file", type=Path, help="Subscription output")
    parser.add_argument(
        "device_id", type=lambda x: int(x, 0), help="Device ID of the update recipient."
    )
    parser.add_argument(
        "start", type=lambda x: int(x, 0), help="Subscription start timestamp"
    )
    parser.add_argument("end", type=int, help="Subscription end timestamp")
    parser.add_argument("channel", type=int, help="Channel to subscribe to")
    return parser.parse_args()


def main():
    """Main function of gen_subscription

    You will likely not have to change this function
    """
    # Parse the command line arguments
    args = parse_args()

    subscription = gen_subscription(
        args.secrets_file.read(), args.device_id, args.start, args.end, args.channel
    )

    # Print the generated subscription for your own debugging
    # Attackers will NOT have access to the output of this (although they may have
    # subscriptions in certain scenarios), but feel free to remove
    #
    # NOTE: Printing sensitive data is generally not good security practice
    logger.debug(f"Generated subscription: {subscription}")

    # Open the file, erroring if the file exists unless the --force arg is provided
    with open(args.subscription_file, "wb" if args.force else "xb") as f:
        f.write(subscription)

    # For your own debugging. Feel free to remove
    logger.success(f"Wrote subscription to {str(args.subscription_file.absolute())}")


if __name__ == "__main__":
    main()
